#[derive(Debug, Default)]
pub struct Status {
    pub auto_shutdown_enabled: bool,
    pub az_home_switch: bool,
    pub az_pos: f32,
    pub azimuth_move_timeout: f32,
    pub cloud_sensor_enabled: bool,
    pub coast: f32,
    pub door_move_timeout: f32,
    pub dropout_door_encoder_closed: u64,
    pub dropout_door_encoder_opened: u64,
    pub dropout_door_pct: f32,
    pub dropout_timer: f32,
    pub encoder_counts: u64,
    pub encoder_counts_per_360: u64,
    pub estop_active: bool,
    pub high_speed: f32,
    pub home_azimuth: f32,
    pub homed: bool,
    pub last_azimuth_goto: f32,
    pub main_door_encoder_closed: u64,
    pub main_door_encoder_opened: u64,
    pub main_door_pct: f32,
    pub move_code: u8,
    pub rain_sensor_enabled: bool,
    pub reversal_delay: f32,
    pub scb_link_ok: bool,
    pub sensor_code: usize,
    pub tolerance: f32,
    pub watchdog_timer: f32,
}
